### ISSUE TITLE
GraphDB License

### ISSUE THREAD

**Issue by tkw1536** [rnsrk/dockerWissKI#1]
What is the license for your GraphDB docker image?

**Comment by rnsrk** [comment]
Since there is no direct provision of libraries, it could be GNU General Public License, Version 2, right?

**Comment by tkw1536** [comment]
I don't know what the license is, you made it.

**Comment by rnsrk** [comment]
^^ yes, but I wonder which license could be fit.

**Comment by rnsrk** [comment]
I've add GPL-3.0 license to the whole repo is this enough?

**Comment by tkw1536** [comment]
According to https://www.drupal.org/project/wisski, WissKI itself is licensed under GPL 2.0. 
IANAL, but as far as I know that's not compatible GPL3 as-is. 

Also you have to double-check if you are allowed to redistribute any software included in the docker images (e.g. drupal, sql, etc) under whatever license you chose.

**Comment by rnsrk** [comment]
Ok

**Comment by rnsrk** [comment]
Since I have no image repositories in dockerhub etc. and everything is downloaded and build local GPL 2.0 should be right.
