### ISSUE TITLE
1 error occurred: 	* Status: COPY failed: file not found in build context or excluded by .dockerignore: stat graphdb.zip: file does not exist, Code: 1

### ISSUE THREAD

**Issue by fishfree** [rnsrk/dockerWissKI#2]
When I run docker-compose up -d. It shows the error as in the title.

**Comment by rnsrk** [comment]
You have to download graphdb free from https://www.ontotext.com/products/graphdb/download/, rename it to "graphdb.zip" and place it in "grapdb_context" dir.
