### ISSUE TITLE
Graphdb image doesn't build

### ISSUE THREAD

**Issue by tla** [rnsrk/dockerWissKI#4]
There is a small fix needed to the GraphDB Dockerfile, in order to avoid build problems. As it is written I get the following error:

```
#0 2.114 mv: target '/graphdb' is not a directory
------
failed to solve: executor failed running [/bin/sh -c unzip /tmp/graphdb.zip -d /tmp &&   mv /tmp/graphdb* /graphdb &&   rm /tmp/graphdb.zip]: exit code: 1
```

The problem is the line 

    mv /tmp/graphdb* /graphdb && \

where the wildcard matches not only the graphdb-10.2.0 directory, but also the graphdb.zip file itself, and so tries (and fails) to move both. I fixed it with

    mv /tmp/graphdb-* /graphdb && \

though you will still have the problem if someone is using GraphDB 9...

**Comment by rnsrk** [comment]
Should be fixed now
